backend:
  name: proxy
  branch: master
  proxy_url: http://localhost:8081/api/v1
  local_backend: true

media_folder: static/img
public_folder: img

collections:
  - name: 'careers'
    label: 'Careers'
    folder: 'content/careers'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Start', name: 'start', widget: 'string' }
  
  - name: 'translations'
    label: 'Translations'
    folder: 'content/translations'
    create: true
    fields:
      - { label: 'translation', name: 'translation', widget: 'string' }