backend:
  name: proxy
  branch: master
  proxy_url: http://localhost:8081/api/v1
  local_backend: true

media_folder: static/img
public_folder: img

collections:
  # - name: 'translations'
  #   label: 'Translations'
  #   folder: 'content/translations'
  #   format: 'frontmatter'
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: 'translation', name: 'translation', widget: 'string' }

  # - name: "navigation"
  #   label: "Navigation"
  #   folder: 'content/navigation'
  #   format: 'frontmatter'
  #   widget: object
  #   collapsed: true
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: "Section title", name: "section_title", widget: string }
  #     - { label: "Section description", name: "section_desc", widget: text }
  #     - { label: "Planet image", name: "planet_image", widget: image }
  #     - { label: "Button modal text", name: "btn_modal", widget: string }
  #     - { label: "Modal title", name: "modal_title", widget: string }
  #     - { label: "Modal content", name: "modal_content", widget: markdown }

  - label: 'Menu'
    name: 'menu'
    folder: 'content/menu'
    format: 'frontmatter'
    widget: 'object'
    collapsed: true
    create: true
    fields:
      - label: 'Links'
        name: 'links_list'
        widget: 'list'
        collapsed: true
        max: 100
        min: 1
        fields:
          - { label: 'Link name', name: 'link_name', widget: string }
          - { label: 'Link path', name: 'link_path', widget: string }
          - label: 'Sublinks'
            name: 'sublinks'
            widget: 'list'
            collapsed: true
            max: 100
            min: 0
            fields:
              - { label: 'Sublink name', name: 'sublink_name', widget: string }
              - { label: 'Sublink path', name: 'link_path', widget: string }

    
